### ISSUE TITLE
Pull Hubot into separate app

### ISSUE THREAD

**Issue by supermitch** [supermitch/streak-podium#1]
I think we should separate the two projects into a hubot script and a python script? Seems like little reason to have the two living under one repo.

**Comment by supermitch** [comment]
We can create a new repo, streak-hubot or something to that effect, for the JS side of things. Not sure how they'll interact, if at all, but can figure that out later.

**Comment by jollyra** [comment]
Ya, that makes sense. It'll get unwieldy having the two forced into the same repo.

**Comment by jollyra** [comment]
You can strip the npm hubot stuff out of this repo. I pulled it out and made a dedicated one here https://github.com/jollyra/hubot-streak-podium
